### ISSUE TITLE
Update Deprecated ioutil Functions for Go 1.16+

### ISSUE THREAD

**Issue by jerichosiahaya** [supabase-community/storage-go#13]
# Chore

## Describe the chore

Update deprecated ioutil functions to the newer alternatives available in Go 1.16 and onwards.

## Additional context

Starting with Go 1.16, several functions in the ioutil package have been deprecated in favor of better named or more appropriate alternatives. For example, ioutil.ReadAll is now recommended to be replaced with io.ReadAll.

By updating these, we can ensure that the codebase stays up-to-date with Go's best practices and reduces any potential technical debt.

Reference: https://pkg.go.dev/io/ioutil#ReadAll

**Comment by tranhoangvuit** [comment]
Thank you @jerichosiahaya for your report. I've made updates in this [PR](https://github.com/supabase-community/storage-go/pull/14). Please let us know if you encounter any issues with the library. I will take a look at it. Thanks.

**Comment by jerichosiahaya** [comment]
> Thank you @jerichosiahaya for your report. I've made updates in this [PR](https://github.com/supabase-community/storage-go/pull/14). Please let us know if you encounter any issues with the library. I will take a look at it. Thanks.

Cool! Thanks
