### ISSUE TITLE
The README could be clearer

### ISSUE THREAD

**Issue by Morgenstern2573** [supabase-community/storage-go#15]
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

README.md

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?
The README left me with questions I could only answer after trying out the library, like what the "abc" in the URL for new client is and what "service-token" means. I also wasn't sure exactly what methods the `client` type had. Also, there's no license specified.

## Describe the improvement

A clear and concise description of the improvement.

Spell all out all the missing and unclear info

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by JanRuettinger** [comment]
To add to the post, I'd appreciate an explanation of the custom error structs.

```Go
type BucketResponseError struct {
	Error      string `json:"error"`
	Message    string `json:"message"`
	StatusCode uint16 `json:"statusCode"`
}
```

How do we check if there is no error? `StatusCode == 0`, `Message empty?`

**Comment by jerichosiahaya** [comment]
Everyone need to refer to the og reference [here](https://supabase.com/docs/reference/javascript/storage-from-upload). This wrapper is still under development and needs a lot of improvement, it would be better if you find something unusual and then fix it, as a contribution to this repository.

**Comment by tranhoangvuit** [comment]
Hi @JanRuettinger , @jerichosiahaya, thank you for your feedback. I will be working on a new version of this library. It should return errors along with data, similar to a JS document. We will also add more options to the parameter object in the function.

**Comment by tranhoangvuit** [comment]
Hi guys, I've updated the README to make it more clear. I'm closing this issue now. If it's still not clear, please feel free to open another issue. We will take a look at it. Thanks!
