### ISSUE TITLE
When managing Buckets the error return type could have a different approach.

### ISSUE THREAD

**Issue by jackgris** [supabase-community/storage-go#17]
# Feature request

When we work with errors, I think could be better if return an error that satisfies the error interface or nil. Also, I believe that is not a good option to panic in this kind of package. Mainly at least for me, is a good practice to avoid panic, for example, my application infrastructure could have a temporary network error and I don't want my application to stop because I forgot to manage the panic. 

## Describe the solution you'd like

I send a pull request like an example code, that needs changes, only with the purpose of showing an option for this issue.

## Describe alternatives you've considered

I think that returning a custom error could be a better option. This is only an observation and another could be a better option.

**Comment by muratmirgun** [comment]
Hi! @tranhoangvuit Can I take this issue?

**Comment by tranhoangvuit** [comment]
Hi @jackgris, based on your PR, I updated the current function to return an error as well. I close this PR first? If you need anything else, please feel free to open another issue.

**Comment by jackgris** [comment]
I saw the update, It's fine to me, thanks.
