### ISSUE TITLE
GetFile method for client

### ISSUE THREAD

**Issue by benjamin-arfa** [supabase-community/storage-go#3]
Hey there :smile: 
I thank you guys a lot for the work, it is helping me in getting started with supabase with my go project.
I needed to get a file from the storage, so I wrote myself a function which fulfills the purpose ...
What do I need to do to contribute haha :laughing: it is my very first time contributing to any open source project.

Bests !!

Ben.

**Comment by NikhilCodes** [comment]
Since this repo doesn't have issues populated quite yet, you can check storage-js or any other libraries available for other languages and check if some issues might happen for this repo, that can be some issue you can reference when you make a PR for it

**Comment by NikhilCodes** [comment]
And also the GetFile function that you have created, is it different from GetPublicUrl/GetSignedUrl which we already have?

P.S. Happy New Year

**Comment by benjamin-arfa** [comment]
Hey Nikhil!
Thanks for the swift response.

To the last message, the method I wrote basically sends a get request and saves thé result in a string. My use case is a texte/csv table. I just checked the getPublicUrl method and it did not respond to my requirements, as it returns a SignedUrl.

I will look into the PR haha.

Thanks a lot a happy new year!
