### ISSUE TITLE
Allow use of streams instead of byte slices

### ISSUE THREAD

**Issue by pzduniak** [supabase-community/storage-go#4]
Hey!

Super happy that library exists, however, I see one serious issue with the API design - there's no way to use an io.Reader / io.Writer (ie. a stream of data), over a byte slice. This isn't a dealbreaker for us right now, but could become one eventually.

If we care about backwards compatibility, I'd suggest creating functions built around io.Readers / io.Writers, implementing the actual functionality , and turning the existing functions into utility wrappers that make it easy to upload / fetch `[]byte`s.

If we don't care about it, I'd suggest dropping the byte slice functions altogether. It encourages bad code practices and it's generally unsupported in the stdlib.

**Comment by NikhilCodes** [comment]
Commit fb1d764718bb4c7c20a63c933f174f73eddedf71 addresses this fix.
v0.5.7 should have this change
